// <auto-generated />
using System;
using GhostList.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GhostList.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GhostList.Domain.Entities.CharonDrop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedMetadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataInitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenderUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId");

                    b.ToTable("CharonDrops");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.CharonViewReceipt", b =>
                {
                    b.Property<Guid>("DropId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DropId", "DeviceId");

                    b.HasIndex("DropId", "UserId");

                    b.ToTable("CharonViewReceipts");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.DailyUsageStat", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ItemsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("ListsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("MembersCreated")
                        .HasColumnType("integer");

                    b.Property<int>("MessagesCreated")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("DailyUsageStats");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.DeviceSubscription", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Locale")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("NotifyOnCharon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotifyOnItemsChanged")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnLethe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotifyOnMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnNemesis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("DeviceId", "ListId");

                    b.HasIndex("DeviceToken");

                    b.HasIndex("ListId");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceSubscriptions");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedSenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<string>("InitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenderNameInitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId");

                    b.ToTable("GhostChatMessages");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedItemsTtl")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("WhisperLifetimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("NemesisSettlementExpiryDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<int>("NemesisSettlementHideAfterDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.HasKey("Id");

                    b.ToTable("GhostLists");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheckedByDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CheckedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<string>("InitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SenderDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenderUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId");

                    b.ToTable("GhostListItems");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostListMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<string>("InitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastReadItemAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastReadMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId", "DeviceId")
                        .IsUnique();

                    b.ToTable("GhostListMembers");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostMessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmojiInitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedSenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenderNameInitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("MessageId", "SenderDeviceId");

                    b.HasIndex("MessageId", "SenderUserId");

                    b.ToTable("GhostMessageReactions");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.InfoMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetPlatform")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("InfoMessages");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.ItemReadReceipt", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("ItemId", "DeviceId");

                    b.HasIndex("ItemId", "UserId");

                    b.ToTable("ItemReadReceipts");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.ItemReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId");

                    b.HasIndex("IsAcknowledged", "RemindAt");

                    b.HasIndex("IsSent", "RemindAt");

                    b.ToTable("ItemReminders");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.ListReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId");

                    b.HasIndex("IsAcknowledged", "RemindAt");

                    b.HasIndex("IsSent", "RemindAt");

                    b.ToTable("ListReminders");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.LocaleStat", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.HasKey("Date", "Language", "Country");

                    b.ToTable("LocaleStats");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.MessageReadReceipt", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("MessageId", "DeviceId");

                    b.HasIndex("MessageId", "UserId");

                    b.ToTable("MessageReadReceipts");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.NemesisExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedReceiptKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadInitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptBlobKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("SplitCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId", "CreatedAt");

                    b.HasIndex("GhostListId", "IsArchived");

                    b.ToTable("NemesisExpenses");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.NemesisSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GhostListId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConfirmedByReceiver")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaidByPayer")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayerDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayerUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReceiverUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadInitializationVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GhostListId");

                    b.HasIndex("GhostListId", "Status");

                    b.ToTable("NemesisSettlements");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.NemesisVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId", "VerifiedByUserId")
                        .IsUnique();

                    b.ToTable("NemesisVerifications");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.CharonDrop", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany()
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.CharonViewReceipt", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.CharonDrop", null)
                        .WithMany()
                        .HasForeignKey("DropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.DeviceSubscription", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostChatMessage", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany("ChatMessages")
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostListItem", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany("Items")
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostListMember", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany()
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostMessageReaction", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostChatMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.ItemReadReceipt", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostListItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.ItemReminder", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany()
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.ListReminder", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany()
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.MessageReadReceipt", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostChatMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.NemesisExpense", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany()
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.NemesisSettlement", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.GhostList", null)
                        .WithMany()
                        .HasForeignKey("GhostListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.NemesisVerification", b =>
                {
                    b.HasOne("GhostList.Domain.Entities.NemesisExpense", null)
                        .WithMany("Verifications")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostList.Domain.Entities.GhostList", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("GhostList.Domain.Entities.NemesisExpense", b =>
                {
                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
