#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const pkg = require('../package.json');
const target = path.join(__dirname, '..', 'src', 'app', 'version.ts');

const content =
    '// This file is auto-generated by scripts/generate-version.js — do not edit manually.\n' +
    `export const APP_VERSION = '${pkg.version}';\n`;

fs.writeFileSync(target, content);
console.log(`Wrote ${target} (version ${pkg.version})`);
